### ISSUE TITLE
Can you give an example of a image in train list file?

### ISSUE THREAD

**Issue by ysc703** [MichalBusta/DeepTextSpotter#10]
Thanks for sharing the codes! It is a nice work!
I want to finetune the model for my own dataset, but confused when preparing for the train list. I have see the code, but failed. I will really appreciate if you can give some examples of the train lists.
Thanks a lot!

**Comment by MichalBusta** [comment]
hi,
the train list is just txt with the image paths. 
each image in the should have corresponding txt file, where each line corresponds to word. 

line example: 
0 0.851475423177 0.247500450534 0.128710019264 0.0338691623536 -0.102781031299 CWRU
cls x y w h alpha txt 

cls - class - not used
x - bbox center.x normalized by image width 
y - bbox center.y normalized by image height 
w - bbox width normalized by image diagonal
h - bbox height normalized by image diagonal
alpha - box angle in radians

**Comment by ysc703** [comment]
Thanks for your quick response! It's very clearly now.

**Comment by qnkhuat** [comment]
Where do we put the file's name?

**Comment by rohitsaluja22** [comment]
Hi we tried train.py but are getting following error:

> 
> I0213 04:00:44.575316 17258 net.cpp:242] This network produces output softmax
> I0213 04:00:44.575346 17258 net.cpp:255] Network initialization done.
> I0213 04:00:44.575435 17258 solver.cpp:56] Solver scaffolding done.
> [416, 416]
> I0213 04:00:44.581261 17258 solver.cpp:330] Iteration 0, Testing net (#0)
> Floating point exception (core dumped)

We are creating a separate .txt file for each .jpeg file. For example, one of the .txt file looks like following:-

> 0 86.544325 113.70325 61.5000988376 10.8000627304 3.03217953614 calliberation


Please help us resolving the error.

**Comment by rohitsaluja22** [comment]
thanks, I got it, I was not normalizing the coordinates and another mistake, the angle calculation was using the right-handed coordinate system, whereas the image follows the left-handed. That's why my angle was 3 radians.
Also, it's not mentioned here but I am giving image path as the first word in the line of train_list.txt. Hope I am right in that?

**Comment by rohitsaluja22** [comment]
file names are to be put in train_list.txt and valid_list.txt. Each file with image_name.txt in foder "img" wherever your training image folder is present.

**Comment by rohitsaluja22** [comment]
Can we give spaces in txt?

**Comment by ustczhouyu** [comment]
> hi,
> the train list is just txt with the image paths.
> each image in the should have corresponding txt file, where each line corresponds to word.
> 
> line example:
> 0 0.851475423177 0.247500450534 0.128710019264 0.0338691623536 -0.102781031299 CWRU
> cls x y w h alpha txt
> 
> cls - class - not used
> x - bbox center.x normalized by image width
> y - bbox center.y normalized by image height
> w - bbox width normalized by image diagonal
> h - bbox height normalized by image diagonal
> alpha - box angle in radians

Hi, MichalBusta, so we don't use class, just x,y,w,h, alpha and txt?

**Comment by MichalBusta** [comment]
> > hi,
> > the train list is just txt with the image paths.
> > each image in the should have corresponding txt file, where each line corresponds to word.
> > line example:
> > 0 0.851475423177 0.247500450534 0.128710019264 0.0338691623536 -0.102781031299 CWRU 
> Hi, MichalBusta, so we don't use class, just x,y,w,h, alpha and txt?

Hi, yes, class has been used to predict language of the text (but it did not not work so well, also we think that the language identification step is not needed: https://arxiv.org/abs/1801.09919)

**Comment by ustczhouyu** [comment]
Thank you very much for your kind reply. I am training the model now. If there are any problems, I will ask you again, please don’t feel disturbed.






At 2018-10-23 16:35:13, "Michal Busta" <notifications@github.com> wrote:


hi,
the train list is just txt with the image paths.
each image in the should have corresponding txt file, where each line corresponds to word.
line example:
0 0.851475423177 0.247500450534 0.128710019264 0.0338691623536 -0.102781031299 CWRU
Hi, MichalBusta, so we don't use class, just x,y,w,h, alpha and txt?

Hi, yes, class has been used to predict language of the text (but it did not not work so well, also we think that the language identification step is not needed: https://arxiv.org/abs/1801.09919)

**Comment by liuqifan67** [comment]
> t

hi ，I just want ask the single txt file is just the list with x，y，w，h and alpha？I tried that before， but its didn't work . the error is RuntimeError: bad lexical cast:source type value could not be interpreted as target. Could you give me some advise？
