### ISSUE TITLE
Can it recognize alphabets only or it is able to recognize number as well?  

### ISSUE THREAD

**Issue by arsalan993** [MichalBusta/DeepTextSpotter#12]

**Comment by MichalBusta** [comment]
Alphabet set: 
 !"#$%&\'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_abcdefghijklmnopqrstuvwxyz{|}~£ÁČĎÉĚÍŇÓŘŠŤÚŮÝŽáčďéěíňóřšťúůýž
