### ISSUE TITLE
Issues while running demo.py

### ISSUE THREAD

**Issue by ayushbits** [MichalBusta/DeepTextSpotter#14]
Hi Michal,
I have installed caffe from [here](https://github.com/BVLC/caffe) and make another installation using darknet branch as you mentioned in README.  However, caffe with darknet installation doesn't satisfy 
`import caffe` dependency. 
I have given both caffe with and without darknet path in PYTHONPATH. However, while running `python demo.py`. I get the following error :

> W0207 17:05:14.716331 25778 _caffe.cpp:142] Net('DeepTextSpotter/models/tiny.prototxt', 1, weights='DeepTextSpotter/models/tiny.caffemodel')
> [libprotobuf ERROR google/protobuf/text_format.cc:274] Error parsing text-format caffe.NetParameter: 513:14: Message type "caffe.LayerParameter" has no field named "reorg_param".
> F0207 17:05:14.717484 25778 upgrade_proto.cpp:88] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: DeepTextSpotter/models/tiny.prototxt
> *** Check failure stack trace: ***
> Aborted (core dumped)

Please tell where I am going wrong.

Specs : 
```

nvcc: NVIDIA (R) Cuda compiler driver
Cuda compilation tools, release 8.0, V8.0.61
```

` NVIDIA-SMI 390.12                 Driver Version: 390.12         `    

`   gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.6) `

**Comment by qnkhuat** [comment]
hi. did u install 2 caffe ?

**Comment by ayushbits** [comment]
Yes, I installed 2 caffe

**Comment by Arenops** [comment]
@ayushbits How to resolve this issue, have any details? I've got a same problem.

**Comment by ayushbits** [comment]
@Arenops Did you install CTC loss layer? Install caffe detailed in this project's Readme file and caffe from official website .

**Comment by Arenops** [comment]
@ayushbits I've forgot to install CTC loss, follow which Readme file? like this ? https://github.com/baidu-research/warp-ctc

**Comment by DreadPiratePsyopus** [comment]
@Arenops I am facing the same problem. Did you install the CTC loss?
