### ISSUE TITLE
Dropout source layer is ignored

### ISSUE THREAD

**Issue by leetwito** [MichalBusta/DeepTextSpotter#18]
Hey,
After the initialization of the network, between the many red lines, I'm also notified that the dropout layer is being ignored:
![image](https://user-images.githubusercontent.com/29614540/36642533-44ab1972-1a49-11e8-85cb-695b04ac3b70.png)

I get this line before every test run.
How can I fix it ?
Thanks,
Lee

**Comment by MichalBusta** [comment]
Hi, 
this is just info level log - in the test time the Dropout layer is always ignored. 
But if you want to get rid of info level messages, just initialize google logging with something like:: 

os.environ['GLOG_minloglevel'] = '5'
