### ISSUE TITLE
Compile error of caffe

### ISSUE THREAD

**Issue by philokey** [MichalBusta/DeepTextSpotter#2]
Hello,

When I build caffe following README, I meet the error:

```
caffe/src/caffe/layers/ondisk_data_layer.cpp:84:65: error: ‘rotatedRectangleIntersection’ was not declared in this scope
``` 
Maybe the branch darknet is missing some code.

**Comment by philokey** [comment]
I removed ondisk_data_layer.cpp/ondisk_data_layer.hpp and then make caffe successfully. However, the package cmp_trie is missing  when I run demo.py

```
ImportError: No module named cmp_trie
```

**Comment by MichalBusta** [comment]
hi, use more recent opencv version. Michal

**Comment by MichalBusta** [comment]
and build projet - I'll fix readme, thanks

**Comment by philokey** [comment]
@MichalBusta Thank you for your answer. Which version should I use and what about the problem of missing cmp_trie?

**Comment by MichalBusta** [comment]
fixed ReadMe - see point 3

**Comment by WangShuaiHefei** [comment]
hi,i when i run the demo.py.here is  the problem following too.
'No module named cmp_trie',i use the opencv3.3

**Comment by MichalBusta** [comment]
Hi Wang, 
please check you are using python2.x and build project (point 3 in ReadMe)
