### ISSUE TITLE
Finding more than one prediction for each TExtBox

### ISSUE THREAD

**Issue by rohitsaluja22** [MichalBusta/DeepTextSpotter#21]
Hey I was thinking if I can find more than one prediction for each TExtBox?
I saw your code uses cmp_trie to decode.. shall I change that with some other search algo? Please suggest...

**Comment by MichalBusta** [comment]
Hi, 
there are many ways, depends on application. 
In case of learning approach you can take some ideas from:  https://arxiv.org/abs/1710.03425

std. trick: 
 - using N-GRAM language model during decoding: we did some experiments with http://www.speech.sri.com/projects/srilm/

**Comment by rohitsaluja22** [comment]
Hey thanks for your reply.. 
Also does detection[1][1] represent confidence in demo.py ?

Why it is greater thank 100 at times?
