### ISSUE TITLE
Reproducing ICDAR Results

### ISSUE THREAD

**Issue by johncorring** [MichalBusta/DeepTextSpotter#22]
Hi,

Thanks for the code.

I've tried to reproduce the reported results for ICDAR 2013 and ICDAR 2015. 

Using the weights you've shared, I get .7 F1 on ICDAR 2013 E2E. In the paper you reported .77. 
I am not using the 90K dictionary for the recogntion. 
Is this drop in performance expected? Are the weights you have shared tuned to some other dataset? 

Regards,
John

**Comment by MichalBusta** [comment]
Hi John, 
this is expected: we shared tiny version of network, which can run real-time on laptops. Full back-bone yolo2 network will increase the numbers. 

Michal
