### ISSUE TITLE
Caffe Make Error

### ISSUE THREAD

**Issue by gengkunling** [MichalBusta/DeepTextSpotter#23]
When I follow the instructions that build the caffe, I have this error:

`/deeplearning/Dropbox/decisionengines/invoice_text_bbox/caffe/src/caffe/layers/ondisk_data_layer.cpp:84:65: error: 'rotatedRectangleIntersection' was not declared in this scope
    int ret = rotatedRectangleIntersection(rect1, rect2, vertices);
                                                                 ^
`

Couldn't find any function that called "rotatedRectangleIntersection" in the src.

**Comment by MichalBusta** [comment]
https://github.com/MichalBusta/DeepTextSpotter/issues/9

**Comment by gengkunling** [comment]
I tried installed the opencv3 using pip, and also tried build from source following this:
[https://github.com/BVLC/caffe/wiki/OpenCV-3.3-Installation-Guide-on-Ubuntu-16.04](url)

But still encountered the same error. .

**Comment by MichalBusta** [comment]
You need full opencv: 
https://github.com/opencv/opencv

or you can comment out the lines causing errors - the function is needed for experiments

**Comment by gengkunling** [comment]
Thanks! I re-installed the opencv3 following this link, now i can build the caffe successfully. 
https://www.learnopencv.com/install-opencv3-on-ubuntu/

**Comment by archanray** [comment]
Apologizing for re-opening a closed issue. Is there any work around to this without building OpenCV from source? I am trying to install it in a server where I don't have sudo access and as such can't install the sudo access libraries for OpenCV.

Thanks.

**Comment by MichalBusta** [comment]
> Apologizing for re-opening a closed issue. Is there any work around to this without building OpenCV from source? I am trying to install it in a server where I don't have sudo access and as such can't install the sudo access libraries for OpenCV.
> 
> Thanks.

2 options: 
 -  comment out lines with rotatedRectangleIntersection 
 - build OpenCV with static libs (cmake option: -D BUILD_SHARED_LIBS=Off)
