### ISSUE TITLE
What is "cls"?

### ISSUE THREAD

**Issue by hanghi** [MichalBusta/DeepTextSpotter#25]
Hello, I am a student and I am very new to the deep learning. I really wanna to know how the training process works.
I see that is the "cls" in the annotation, what is that, could you please explain it to me?

Thanks a lot.

**Comment by MichalBusta** [comment]
Hello,
cls mean class of the object. (not used now) 
we use this for experiments with joint detection of multiple classes (text/face/ ...) and for  script identification.

**Comment by hanghi** [comment]
Thank you very much :D
