### ISSUE TITLE
Caffe Compiling Error "__shfl_down" undefine

### ISSUE THREAD

**Issue by whulc** [MichalBusta/DeepTextSpotter#26]
Hey:
    I tried to compile Caffe following the instructions, and met this error:
`/caffe/src/caffe/layers/reduce.cu(44) error : identifier "__shfl_down" is undefined`
    The function "__shfl_down" should be defined in cuda. However, in the file reduce.cu, quote of cuda are commented. 
`// Includes, system
// #include <stdio.h>
// #include <stdlib.h>

// Includes, cuda
// #include <cuda_runtime.h>
// #include <cublas_v2.h>

// Includes, cuda helper functions
// #include <helper_cuda.h>

// For the functors
#include "caffe/util/ctc/detail/ctc_helper.h"
#include "caffe/util/ctc/ctc.h"
`

**Comment by MichalBusta** [comment]
based on https://github.com/tensorflow/tensorflow/issues/1361
you need gpu with 3.0 compute capability

**Comment by whulc** [comment]
Thank  you, I use another device and make through it.

**Comment by mit456** [comment]
@MichalBusta I faced the same issue, I checked my CUDA capability and found it has 5.0, isn't enough?  I have attached screenshot.
OS: Ubuntu 18.04 LTS

![screenshot_2018-06-12_16-13-41](https://user-images.githubusercontent.com/4567139/41285989-9e964d56-6e5b-11e8-8a80-0d55db008d3f.png)

**Comment by mattroos** [comment]
@mit456 and @MichalBusta , I'm getting this error too.  Using a GTX 970 (compute capacity 5.2) with CUDA 7.5, NVIDIA driver 375.66.  Any thoughts?  @MichalBusta , what version of CUDA do you suggest?

**Comment by MichalBusta** [comment]
GTX 970 is ok. 
The problem is in caffe build script -  by default it compiles sources for all cuda archs. 
you can pass the -D CUDA_ARCH_NAME= ...  to cmake

**Comment by JeanMaximilienCadic** [comment]
Try to move from cuda 10.1 to cuda 9.1 `sudo apt install nvidia-cuda-toolkit` and `gcc-7` to `gcc-5` . It worked for me after trying all solutions available so far.
