### ISSUE TITLE
License for various tools used in DTS ?

### ISSUE THREAD

**Issue by ayushbits** [MichalBusta/DeepTextSpotter#30]
Hi Michal,

Can you outline license of various tools used in DTS and overall license for DTS ?

Regards,
Ayush

**Comment by MichalBusta** [comment]
Hi Ayush,

caffe - BSD 2 (but you want do some  more research here - patent issues on some specific layers etc.)
warp-ctc - Apache 2.0
opencv - BSD 3 

sample models has been trained on OS datasets which forbids commercial use - so you will have to train on your own data or contact VGG group and ICDAR  group or permission/licence
