### ISSUE TITLE
Classes in published weight file, (w,h,\theta) ambiguity

### ISSUE THREAD

**Issue by johncorring** [MichalBusta/DeepTextSpotter#31]
I noticed that in the published model you have 6 classes in the region layer (so the shape of conv_22 is 1024x*x*x168). But in the datasets mentioned in the paper there is only 1 language afaik. Do you use an additional training set that came in handy? 

Also, there is inherent ambiguity in (w,h, \theta) in rotated boxes. It seems like you handle this by asserting w > h, but it is not 100% clear from the paper or the code.

Thanks and regards,
John

**Comment by MichalBusta** [comment]
Hi John,

2018-04-10 18:32 GMT+02:00 John Corring <notifications@github.com>:

> I noticed that in the published model you have 6 classes in the region
> layer (so the shape of conv_22 is 1024x*x*x168). But in the datasets
> mentioned in the paper there is only 1 language afaik. Do you use an
> additional training set that came in handy?
>
There is also new ICDAR MLT dataset, Chinese RCTW-17 dataset, also ours
synthetic still not released dataset for MLT (
https://arxiv.org/abs/1801.09919). It is easy to remove un-used filters.

> Also, there is inherent ambiguity in (w,h, \theta) in rotated boxes. It
> seems like you handle this by asserting w > h, but it is not 100% clear
> from the paper or the code.
>
this "asserting w > h" comes from later experiments on MLT Dataset - the
annotation in this dataset is not consistent - for getting good numbers on
icdar 2013/2015 dataset, you do not want your model to learn angle (+- 10
degrees and it is enough - more will hurt your numbers) - training takes
longer etc. - you do not want shoot yourself into leg as we did,  For
webcam demo,  it is good to go for bigger rotations during the training.

Michal

**Comment by johncorring** [comment]
Yes the ambiguity on the angle and width/height is obvious, but I was not sure how you are handling it.

Thanks Michal!
