### ISSUE TITLE
INTERSECT_NONE is not a member of cv when making project

### ISSUE THREAD

**Issue by joeliven** [MichalBusta/DeepTextSpotter#38]
Hi @MichalBusta, 

When I go to make the project I'm getting this error:
```root@0825c99f78d2:/workspace/DeepTextSpotter/build# make
Scanning dependencies of target trie_py
[ 25%] Building CXX object src/CMakeFiles/trie_py.dir/trie.cpp.o
/workspace/DeepTextSpotter/src/trie.cpp: In function 'PyArrayObject* assign_lines(PyArrayObject*, int, npy_intp*, PyArrayObject*, npy_intp*)':
/workspace/DeepTextSpotter/src/trie.cpp:300:65: error: 'rotatedRectangleIntersection' was not declared in this scope
    int ret = rotatedRectangleIntersection(rect1, rect2, vertices);
                                                                 ^
/workspace/DeepTextSpotter/src/trie.cpp:301:14: error: 'INTERSECT_NONE' is not a member of 'cv'
    if(ret != cv::INTERSECT_NONE){
              ^
src/CMakeFiles/trie_py.dir/build.make:62: recipe for target 'src/CMakeFiles/trie_py.dir/trie.cpp.o' failed
make[2]: *** [src/CMakeFiles/trie_py.dir/trie.cpp.o] Error 1
CMakeFiles/Makefile2:124: recipe for target 'src/CMakeFiles/trie_py.dir/all' failed
make[1]: *** [src/CMakeFiles/trie_py.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
root@0825c99f78d2:/workspace/DeepTextSpotter/build#```

Any suggestions? I'm running this inside the official caffe docker image found here:
https://github.com/BVLC/caffe/tree/master/docker

Also,  do you know of any tensorflow implementation of Deep TextSpotter? I've searched around and can't seem to find one.

Thanks!
Joel

**Comment by MichalBusta** [comment]
Hi Joel,

On 05/25/2018 05:51 AM, Joel Iventosch wrote:
>
> Hi @MichalBusta <https://github.com/MichalBusta>,
>
> When I go to make the project I'm getting this error:
>
> |Scanning dependencies of target trie_py [ 25%] Building CXX object 
> src/CMakeFiles/trie_py.dir/trie.cpp.o 
> /workspace/DeepTextSpotter/src/trie.cpp: In function 'PyArrayObject* 
> assign_lines(PyArrayObject*, int, npy_intp*, PyArrayObject*, 
> npy_intp*)': /workspace/DeepTextSpotter/src/trie.cpp:300:65: error: 
> 'rotatedRectangleIntersection' was not declared in this scope int ret 
> = rotatedRectangleIntersection(rect1, rect2, vertices); ^ 
> /workspace/DeepTextSpotter/src/trie.cpp:301:14: error: 
> 'INTERSECT_NONE' is not a member of 'cv' if(ret != 
> cv::INTERSECT_NONE){ ^ src/CMakeFiles/trie_py.dir/build.make:62: 
> recipe for target 'src/CMakeFiles/trie_py.dir/trie.cpp.o' failed 
> make[2]: *** [src/CMakeFiles/trie_py.dir/trie.cpp.o] Error 1 
> CMakeFiles/Makefile2:124: recipe for target 
> 'src/CMakeFiles/trie_py.dir/all' failed make[1]: *** 
> [src/CMakeFiles/trie_py.dir/all] Error 2 Makefile:83: recipe for 
> target 'all' failed make: *** [all] Error 2 
> root@0825c99f78d2:/workspace/DeepTextSpotter/build#``` Any 
> suggestions? I'm running this inside the official caffe docker image 
> found here: https://github.com/BVLC/caffe/tree/master/docker|
|wrong version of OpenCV. |
> |Also, do you know of any tensorflow implementation of Deep 
> TextSpotter? I've searched around and can't seem to find one.|
|It is now out-dated project (still usable for certain applications, but 
...). SOTA in text detection is based on dense predictions, so I would 
recommend to use EAST detector (with TF implementation: 
https://github.com/argman/EAST)
|

**Comment by joeliven** [comment]
Thanks @MichalBusta appreciate the quick response. A few related questions when you have a chance:
(1) What is the correct version of OpenCV to be using?
(2) What is the correct version Caffe? Should we be using your darknet version, or will the standard caffe repo work? If so, which version?
(3) Regarding EAST, I came across that and it looks great for text detection, but it appears to be only text **detection**, but not text **recognition**. My understanding is that Deep TextSpotter does both text detection and recognition, while EAST does only the detection. Is that correct, or am I off-base on that?
Many thanks!!
