### ISSUE TITLE
What do you mean by greedy prefix decoding?

### ISSUE THREAD

**Issue by DreadPiratePsyopus** [MichalBusta/DeepTextSpotter#40]
Hello @MichalBusta ,
At the main page it says that 
"For decoding final output, we provide just greedy and dictionary based prefix decoding"
What do you mean by greedy prefix decoding? Is it basically to recognize out of vocabulary words?

Thanks for your anwer.

**Comment by MichalBusta** [comment]
Hello Pirate,

On 05/28/2018 05:13 PM, DreadPiratePsyopus wrote:
>
> Hello @MichalBusta <https://github.com/MichalBusta> ,
> At the main page it says that
> "For decoding final output, we provide just greedy and dictionary 
> based prefix decoding"
> What do you mean by greedy prefix decoding? Is it basically to 
> recognize out of vocabulary words?
>
it is not greedy prefix decoding but greedy and prefix decoding:
  - greedy = "incorrect" way how to decode softmax = take local maximum 
(correct way is to do full dyn. programing, but it brings you just 1% 
improvement)
  - prefix decoding = beam search with dictionary = take local maximum 
which leads to leaf node (dict. word)
