### ISSUE TITLE
Single Characters are not recognized

### ISSUE THREAD

**Issue by mowkee** [MichalBusta/DeepTextSpotter#49]
Is it possible to detect single characters? for example the word " T Segments" the word "Segments" is recognized but "T" is not (There is more than single space between "T" and "Segments"). A bounding box is drawn around it though but it won't appear on the std out like the "Segments" word. Is it possible to change this behavior?

**Comment by Gitchenguang** [comment]
I changed the codes 
For process_splits in utils.py 
line 288: if len(text) > 2 and ( text.isdigit() or is_dict): --> if len(text) > 0 and ( text.isdigit() or is_dict):
For demo.py
line 164: if len(det_text) < 3 and mean_conf < 0.8:  -->  if len(det_text) < 1 and mean_conf < 0.8: 
and it will appear now

**Comment by mowkee** [comment]
Yeah I dug deep and found it myself but forgot to come and update here. You beat me to it. I confirm that this solution works incase anyone is interested in the future.
