### ISSUE TITLE
where is bilinear sampling used in the code?

### ISSUE THREAD

**Issue by blackyang** [MichalBusta/DeepTextSpotter#5]
Thanks for sharing the code. I am training to understand the paper, so where is bilinear sampling used in the code? From the code it seems that after getting bounding boxes proposals, you just crop the original image?

**Comment by MichalBusta** [comment]
Hello Xiao,

On 11/08/2017 05:59 AM, Xiao Yang wrote:
>
> Thanks for sharing the code. I am training to understand the paper, so 
> where is bilinear sampling used in the code? From the code it seems 
> that after getting bounding boxes proposals, you just crop the 
> original image?
>
the shared version takes raw image with bilinear interpolation ( ~= crop 
the original image), the option with getting features also works but 
there is trade-off - your detector have to run on larger images (= 
slower runtime). Michal

**Comment by blackyang** [comment]
Thanks!
