### ISSUE TITLE
demo.py issue

### ISSUE THREAD

**Issue by yuechenfeng** [MichalBusta/DeepTextSpotter#51]
Dear Michal: 
Error parsing text-format caffe.NetParameter: 513:14: Message type "caffe.LayerParameter" has no field named "reorg_param".

I have the same issue as the issue 14. So I rebuild my Darknet based on the installation. However, I don't know how to add warp_ctc to my darknet. And I notice the current version of the Darknet seems to have its own ctc implementation.  Any suggestion for my issue?
By the way, is there any docker image which can easily run the demo?

[https://github.com/MichalBusta/DeepTextSpotter/issues/14](url)

Best regard. Thank you for your help.

**Comment by MichalBusta** [comment]
Hi yuechenfeng,


On 20/08/18 06:02, yuechenfeng wrote:
>
> Dear Michal:
> Error parsing text-format caffe.NetParameter: 513:14: Message type 
> "caffe.LayerParameter" has no field named "reorg_param".
>
the error mean that python is not seeing proper version of caffe.
   - you can check python path
   - or force python path to use build version by :
import sys
sys.path.insert(0, 'path to your caffe install path')

  - or you forgot to checkout proper branch during caffe instalation

|git checkout darknet|

> I have the same issue as the issue 14. So I rebuild my Darknet based 
> on the installation. However, I don't know how to add warp_ctc to my 
> darknet. And I notice the current version of the Darknet seems to have 
> its own ctc implementation. Any suggestion for my issue?
> By the way, is there any docker image which can easily run the demo?
>
no docker image :(

**Comment by yuechenfeng** [comment]
Thank you very much!
