### ISSUE TITLE
GenericVocabulary file content

### ISSUE THREAD

**Issue by mohammadSadeq** [MichalBusta/DeepTextSpotter#59]
Can you please provide me of with does the GenericVocabulary.txt file that is referenced in validation.py line 409  cmp_trie.load_dict('/home/busta/data/icdar2013-Test/GenericVocabulary.txt') contain.
and an example of its content

**Comment by MichalBusta** [comment]
http://rrc.cvc.uab.es/?ch=4&com=downloads

**Comment by mohammadSadeq** [comment]
Thank you
