### ISSUE TITLE
data-dir file content

### ISSUE THREAD

**Issue by mohammadSadeq** [MichalBusta/DeepTextSpotter#61]
@MichalBusta  
What is the content of the file referenced at line 407 train.py
parser.add_argument('-data_dir', default='/mnt/textspotter/tmp/SynthText')

and please why do we need it since the image paths are in train_list.txt??

and content of train_icdar.txt referenced at line 7 tiny.prototxt
data_param { source: "/home/busta/data/SynthText/train_icdar.txt" }

Thank you

**Comment by MichalBusta** [comment]
train_list.txt can contain relative paths (to data_dir)
