### ISSUE TITLE
Error while running train.py

### ISSUE THREAD

**Issue by johncorring** [MichalBusta/DeepTextSpotter#8]
After formatting SynthText to conform to the x,y,w,h,ang format I run into a problem while training. 

Traceback (most recent call last):
  File "train_v0.py", line 431, in <module>
    train_dir(nets, sgd, yolonet, dataloader, args)
  File "train_v0.py", line 406, in train_dir
    process_batch(nets, optim, optim2, image_size, args)
  File "train_v0.py", line 126, in process_batch
    cx = net.layers[0].get_crop(bid, 0)
AttributeError: 'Layer' object has no attribute 'get_crop'

Apparently, OnDiskData is registered (I think you named in CMPData) and python has access to basic things like the ``type'' function, but ``get_img_file_name'' and ``get_crop'' are not accessible. Is this training code verified to run? Have you encountered this behavior?

**Comment by MichalBusta** [comment]
Hi, I'll fix this - I forgot to commit python bindings changes. Michal

**Comment by johncorring** [comment]
Thanks for the quick reply, let me know when it is up and I'll close.

**Comment by johncorring** [comment]
It looks like this issue is closed.

**Comment by ysc703** [comment]
@MichalBusta @johncorring 
I have met the same problem, but I don't know how to fix it as above. 
Can you give me more detail information about the solution.
Thanks.

**Comment by ysc703** [comment]
Yey, I found it in the _caffe.cpp!
I changed to another _caffe.cpp file yesterday for windows, but forgot the difference for the new layer.
