### ISSUE TITLE
Issue in step 2 : "error: ‘rotatedRectangleIntersection’ was not declared in this scope"

### ISSUE THREAD

**Issue by waqasamjad1** [MichalBusta/DeepTextSpotter#9]
After following the steps from the link ,

when i make after this command , cmake -D CMAKE_BUILD_TYPE=Release -D BLAS=Open -D BUILD_SHARED_LIBS=Off ..

error: ‘rotatedRectangleIntersection’ was not declared in this scope
int ret = rotatedRectangleIntersection(rect1, rect2, vertices);

https://imgur.com/phG2YrU

Kindly Help

**Comment by j6k4m8** [comment]
@waqasamjad1 can you mention how you got around this error?

**Comment by j6k4m8** [comment]
For search-result posterity; this is a misconfigured or out-of-date OpenCV. Rebuild opencv from source or reinstall and this should be fixed.

**Comment by j6k4m8** [comment]
...thanks Old Me, for fixing New Me's problem
